### ISSUE TITLE
tabs with anchor tags with href having a slash following the hash causes an error

### ISSUE THREAD

**Issue by ancientdemon** [Dogfalo/materialize#2848]
When anchor tags in tabs are defined with a forward slash ('/') following the hash ('#') like href='#/link' (this is an angular route) this causes an error at runtime.

![image](https://cloud.githubusercontent.com/assets/15957098/13376607/4e15be62-dd8e-11e5-8022-8cf771f560bf.png)

The error seen in the console is as follows

Error: Syntax error, unrecognized expression: #/troubledAccountList
    at Function.ga.error (http://localhost:9558/bower_components/jquery/dist/jquery.min.js:2:12481)
    at ga.tokenize (http://localhost:9558/bower_components/jquery/dist/jquery.min.js:2:18408)
    at ga.select (http://localhost:9558/bower_components/jquery/dist/jquery.min.js:2:21136)
    at Function.ga [as find](http://localhost:9558/bower_components/jquery/dist/jquery.min.js:2:7114)
    at n.fn.extend.find (http://localhost:9558/bower_components/jquery/dist/jquery.min.js:2:23410)
    at n.fn.init (http://localhost:9558/bower_components/jquery/dist/jquery.min.js:2:23954)
    at n (http://localhost:9558/bower_components/jquery/dist/jquery.min.js:2:405)
    at HTMLAnchorElement.<anonymous> (http://localhost:9558/bower_components/materialize/dist/js/materialize.js:1236:9)
    at Function.n.extend.each (http://localhost:9558/bower_components/jquery/dist/jquery.min.js:2:2882)
    at n.fn.n.each (http://localhost:9558/bower_components/jquery/dist/jquery.min.js:2:847) undefined

line that causes the error in materialize.js is

```
  // Hide the remaining content
  $links.not($active).each(function () {
    $(this.hash).hide();
  });
```

update: someone has asked the same question stackoverlfow

http://stackoverflow.com/questions/34986418/sliding-tab-indicator-of-materializecss-tab-disappears-on-adding-href-as-name

**Comment by Tk-archer** [comment]
+1
i think we can use `data-href='#id'` to replace `href='#id'`

**Comment by ancientdemon** [comment]
Thanks @Tk-archer , but I could not figure out how the navigation works upon clicking the tab when you use data-href='#id'. Now there is no error displayed in console but navigation does not work either. Could you kindly point to an example implementation?

**Comment by itsmejustind** [comment]
I was able to get rid of the error by commenting out 3 lines in materialize.js. Version 0.97.7. Line 1272, 1296, and 1323. It doesn't appear to have any effect on my app other than removing the error. I hope the devs look into this.

Here is my post on SO – http://stackoverflow.com/questions/39902673/jquery-syntax-error-unrecognized-expression-using-angular-angular-ui-router-an

**Comment by itsmejustind** [comment]
@ancientdemon is right. data-href="#/asdf" works for me. Working Fiddle – https://jsfiddle.net/whatisthebigpicture/rj08fosn/

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.

**Comment by huww98** [comment]
This is not fixed, vue.js always generate `href` for `router-link` template element. so I created #5291 to fix this.
