### ISSUE TITLE
Meteor 1.4: fourseven:scss is too old

### ISSUE THREAD

**Issue by diegonc** [Dogfalo/materialize#3446]
Meteor 1.4 upgraded the version of node it runs on. As a result, the scss dependency no longer works and needs to be updated to a newer version.

As a workaround you can install scss in advance:

    $ meteor add fourseven:scss
    $ meteor add materialize:materialize@0.97.7

so it gets the latest version of scss; the second add won't downgrade nor conflict with it.

Here's the error message just in case other are looking it up.
```
$ meteor add materialize:materialize
 => Errors while adding packages:             
                                              
While loading package fourseven:scss@3.2.0:
error: Command failed:
/home/diego/.meteor/packages/meteor-tool/.1.4.0-1.gbcz17++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
Cannot download
"https://github.com/sass/node-sass/releases/download/v3.2.0/linux-x64-46_binding.node":
HTTP error 404 Not Found
gyp: /home/diego/.node-gyp/4.4.7/common.gypi not found (cwd:
/home/diego/.meteor/packages/fourseven_scss/.3.2.0.yhj1pt++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6an9hx/node_modules/node-sass)
while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit
(/home/diego/.meteor/packages/fourseven_scss/.3.2.0.yhj1pt++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6an9hx/node_modules/node-sass/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-42-generic
gyp ERR! command
"/home/diego/.meteor/packages/meteor-tool/.1.4.0-1.gbcz17++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/diego/.meteor/packages/fourseven_scss/.3.2.0.yhj1pt++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6an9hx/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
"rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd
/home/diego/.meteor/packages/fourseven_scss/.3.2.0.yhj1pt++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6an9hx/node_modules/node-sass
gyp ERR! node -v v4.4.7
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv
"/home/diego/.meteor/packages/meteor-tool/.1.4.0-1.gbcz17++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/diego/.meteor/packages/meteor-tool/.1.4.0-1.gbcz17++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node
scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/diego/.meteor/packages/fourseven_scss/.3.2.0.yhj1pt++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6an9hx/npm-debug.log
Cannot download
"https://github.com/sass/node-sass/releases/download/v3.2.0/linux-x64-46_binding.node":
HTTP error 404 Not Found
gyp: /home/diego/.node-gyp/4.4.7/common.gypi not found (cwd:
/home/diego/.meteor/packages/fourseven_scss/.3.2.0.yhj1pt++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6an9hx/node_modules/node-sass)
while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit
(/home/diego/.meteor/packages/fourseven_scss/.3.2.0.yhj1pt++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6an9hx/node_modules/node-sass/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-42-generic
gyp ERR! command
"/home/diego/.meteor/packages/meteor-tool/.1.4.0-1.gbcz17++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/diego/.meteor/packages/fourseven_scss/.3.2.0.yhj1pt++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6an9hx/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
"rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd
/home/diego/.meteor/packages/fourseven_scss/.3.2.0.yhj1pt++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6an9hx/node_modules/node-sass
gyp ERR! node -v v4.4.7
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv
"/home/diego/.meteor/packages/meteor-tool/.1.4.0-1.gbcz17++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/diego/.meteor/packages/meteor-tool/.1.4.0-1.gbcz17++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node
scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/diego/.meteor/packages/fourseven_scss/.3.2.0.yhj1pt++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6an9hx/npm-debug.log
```

**Comment by Dogfalo** [comment]
See #3438
