### ISSUE TITLE
ERROR in ./~/materialize-css/fonts/roboto/Roboto-Bold.ttf

### ISSUE THREAD

**Issue by myoneray** [Dogfalo/materialize#3823]
`npm  run dev`

**resule-->**
`> @1.0.0 dev /home/upsmart/GIT/gitHub/angular-ES6-material-webpack

> webpack-dev-server --port 9100 --progress --colors

  0% compile http://localhost:9100/webpack-dev-server/
webpack result is served from /
content is served from /home/upsmart/GIT/gitHub/angular-ES6-material-webpack
 51% 18/26 build modulesContainer#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#style() is deprecated. Use Node#raw()
Container#remove is deprecated. Use Container#removeChild
Node#before is deprecated. Use Node#raws.before
 68% 30/31 build modulesNode#_value was deprecated. Use Node#raws.value
Hash: de383e3d0b47f811bc24  
Version: webpack 1.13.2
Time: 3048ms
                        Asset       Size  Chunks             Chunk Names
   templates/home-832769.html    1.73 kB          [emitted]  
templates/sidenav-026891.html  264 bytes          [emitted]  
             bundle-de383e.js    4.05 MB       0  [emitted]  main
                   index.html  684 bytes          [emitted]  
chunk    {0} bundle-de383e.js (main) 3.97 MB [rendered]
    [0] ./lib/index.js 2.04 kB {0} [built] [1 error]
    [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
    [2] ./~/jquery/dist/jquery.js 258 kB {0} [built]
    [3] ./~/style-loader/addStyles.js 6.09 kB {0} [built]
    [4] ./~/angular-animate/index.js 60 bytes {0} [built]
    [5] ./~/angular/index.js 48 bytes {0} [built]
    [6] ./~/angular-animate/angular-animate.js 147 kB {0} [built]
    [7] ./~/angular-aria/angular-aria.js 14.6 kB {0} [built]
    [8] ./~/angular-aria/index.js 54 bytes {0} [built]
    [9] ./~/angular-material/angular-material.js 1.13 MB {0} [built]
   [10] ./~/angular-material/index.js 270 bytes {0} [built]
   [11] ./~/angular-ui-router/release/angular-ui-router.js 170 kB {0} [built]
   [12] ./~/angular/angular.js 1.1 MB {0} [built]
   [13] ./~/css-loader!./~/angular-material/angular-material.css 743 kB {0} [built]
   [14] ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./lib/home/home.scss 1.86 kB {0} [built]
   [15] ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./lib/scss/bootstrap.scss 451 bytes {0} [built]
   [16] ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./~/materialize-css/sass/materialize.scss 168 kB {0} [built] [20 errors]
   [17] ./lib/home/home.html 72 bytes {0} [built]
   [18] ./lib/sidenav/sidenav.html 75 bytes {0} [built]
   [19] ./~/hammerjs/hammer.js 73.8 kB {0} [built]
   [20] ./~/materialize-css/bin/materialize.js 138 kB {0} [built]
   [26] ./lib/home/home.config.js 1.62 kB {0} [built]
   [27] ./lib/home/home.controller.js 2.34 kB {0} [built]
   [28] ./lib/home/home.module.js 678 bytes {0} [built]
   [29] ./lib/sidenav/sidenav.controller.js 559 bytes {0} [built]
   [30] ./lib/sidenav/sidenav.module.js 540 bytes {0} [built]
   [31] ./~/angular-material/angular-material.css 888 bytes {0} [built]
   [32] ./lib/home/home.scss 1.2 kB {0} [built]
   [33] ./lib/scss/bootstrap.scss 1.21 kB {0} [built]
   [34] ./~/materialize-css/sass/materialize.scss 1.09 kB {0} [built]
   [35](webpack)/buildin/amd-options.js 43 bytes {0} [built]

ERROR in ./lib/index.js
Module not found: Error: Cannot resolve module 'font-awesome/css/font-awesome.css' in /home/upsmart/GIT/gitHub/angular-ES6-material-webpack/lib
 @ ./lib/index.js 15:0-44

ERROR in ./~/materialize-css/fonts/roboto/Roboto-Thin.eot
Module parse failed: /home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/materialize-css/fonts/roboto/Roboto-Thin.eot Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)
    at Parser.pp$4.raise (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:439:3)
 @ ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./~/materialize-css/sass/materialize.scss 2:75496-75538 2:75557-75599

ERROR in ./~/materialize-css/fonts/roboto/Roboto-Light.eot
Module parse failed: /home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/materialize-css/fonts/roboto/Roboto-Light.eot Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)
    at Parser.pp$4.raise (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:439:3)
 @ ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./~/materialize-css/sass/materialize.scss 2:75961-76004 2:76023-76066

ERROR in ./~/materialize-css/fonts/roboto/Roboto-Thin.woff2
Module parse failed: /home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/materialize-css/fonts/roboto/Roboto-Thin.woff2 Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '' (1:4)
    at Parser.pp$4.raise (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.pp$7.next (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2413:10)
    at Parser.pp$3.parseIdent (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2191:10)
    at Parser.pp$3.parseExprAtom (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1774:21)
    at Parser.pp$3.parseExprSubscripts (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:516:17)
 @ ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./~/materialize-css/sass/materialize.scss 2:75647-75691

ERROR in ./~/materialize-css/fonts/roboto/Roboto-Thin.woff
Module parse failed: /home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/materialize-css/fonts/roboto/Roboto-Thin.woff Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '' (1:4)
    at Parser.pp$4.raise (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.pp$7.next (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2413:10)
    at Parser.pp$3.parseIdent (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2191:10)
    at Parser.pp$3.parseExprAtom (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1774:21)
    at Parser.pp$3.parseExprSubscripts (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:516:17)
 @ ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./~/materialize-css/sass/materialize.scss 2:75720-75763

ERROR in ./~/materialize-css/fonts/roboto/Roboto-Light.woff2
Module parse failed: /home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/materialize-css/fonts/roboto/Roboto-Light.woff2 Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '' (1:4)
    at Parser.pp$4.raise (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.pp$7.next (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2413:10)
    at Parser.pp$3.parseIdent (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:2191:10)
    at Parser.pp$3.parseExprAtom (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1774:21)
    at Parser.pp$3.parseExprSubscripts (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/acorn/dist/acorn.js:516:17)
 @ ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./~/materialize-css/sass/materialize.scss 2:76114-76159

ERROR in ./~/materialize-css/fonts/roboto/Roboto-Thin.ttf
Module parse failed: /home/upsmart/GIT/gitHub/angular-ES6-material-webpack/node_modules/materialize-css/fonts/roboto/Roboto-Thin.ttf Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.`

**config  packge.json-->**
`"dependencies": {
    "angular": "~1.4.8",
    "angular-animate": "~1.4.8",
    "angular-aria": "~1.4.8",
    "angular-material": "^1.0.0",
    "angular-ui-router": "^0.2.14"
  },
  "devDependencies": {
    "autoprefixer-loader": "^2.0.0",
    "babel-core": "^5.2.9",
    "babel-loader": "^5.0.0",
    "css-loader": "^0.12.0",
    "file-loader": "^0.8.1",
    "html-loader": "^0.3.0",
    "html-webpack-plugin": "^1.3.0",
    "materialize-css": "^0.97.7",
    "ng-annotate-loader": "~0.0.4",
    "node-sass": "^3.2.0",
    "path": "^0.11.14",
    "sass-loader": "^1.0.2",
    "style-loader": "^0.12.1",
    "webpack": "^1.8.11",
    "webpack-dev-server": "^1.8.2"
  }`

**Comment by cjaoude** [comment]
the font shouldn't even be a local dependency. it should be imported in straight from Google Fonts

just sayin'
