### ISSUE TITLE
Error thrown while adding materialize:materialize package into fresh app  (Meteor v1.4.2.3)

### ISSUE THREAD

**Issue by deepupathak** [Dogfalo/materialize#4011]
Hello Guys,
I have got the following error while adding materialize:materialize package into a fresh app (Meteor v1.4.2.3)

```
 => Errors while adding packages:             
                                              
While loading package fourseven:scss@3.2.0:
error: Command failed: /home/divyanshu/.meteor/packages/meteor-tool/.1.4.2_3.yimmd4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --update-binary
Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/linux-x64-46_binding.node": HTTP error 404 Not Found
gyp: /home/divyanshu/.node-gyp/4.6.2/common.gypi not found (cwd:
/home/divyanshu/.meteor/packages/fourseven_scss/.3.2.0.1rcwr5k++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s687zv/node_modules/node-sass)
while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit
(/home/divyanshu/.meteor/packages/fourseven_scss/.3.2.0.1rcwr5k++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.4.0-53-generic
gyp ERR! command "/home/divyanshu/.meteor/packages/meteor-tool/.1.4.2_3.yimmd4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/divyanshu/.meteor/packages/fourseven_scss/.3.2.0.1rcwr5k++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s687zv/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
"rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd
/home/divyanshu/.meteor/packages/fourseven_scss/.3.2.0.1rcwr5k++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s687zv/node_modules/node-sass
gyp ERR! node -v v4.6.2
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/home/divyanshu/.meteor/packages/meteor-tool/.1.4.2_3.yimmd4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/divyanshu/.meteor/packages/meteor-tool/.1.4.2_3.yimmd4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "rebuild" "--update-binary"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/divyanshu/.meteor/packages/fourseven_scss/.3.2.0.1rcwr5k++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s687zv/npm-debug.log
Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/linux-x64-46_binding.node": HTTP error 404 Not Found
gyp: /home/divyanshu/.node-gyp/4.6.2/common.gypi not found (cwd:
/home/divyanshu/.meteor/packages/fourseven_scss/.3.2.0.1rcwr5k++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s687zv/node_modules/node-sass)
while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit
(/home/divyanshu/.meteor/packages/fourseven_scss/.3.2.0.1rcwr5k++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.4.0-53-generic
gyp ERR! command "/home/divyanshu/.meteor/packages/meteor-tool/.1.4.2_3.yimmd4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/divyanshu/.meteor/packages/fourseven_scss/.3.2.0.1rcwr5k++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s687zv/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
"rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd
/home/divyanshu/.meteor/packages/fourseven_scss/.3.2.0.1rcwr5k++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s687zv/node_modules/node-sass
gyp ERR! node -v v4.6.2
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/home/divyanshu/.meteor/packages/meteor-tool/.1.4.2_3.yimmd4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/divyanshu/.meteor/packages/meteor-tool/.1.4.2_3.yimmd4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "rebuild" "--update-binary"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/divyanshu/.meteor/packages/fourseven_scss/.3.2.0.1rcwr5k++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-s687zv/npm-debug.log

```

Please give me the solution for this issue.
Thanks

**Comment by tomscholz** [comment]
Looks like a problem with fourseven:scss, not materialize! Please ask the author of the fourseven:scss package!
