### ISSUE TITLE
Upgrading to 0.98.0 from 0.97.1 fails meteor app

### ISSUE THREAD

**Issue by juicycleff** [Dogfalo/materialize#4321]
### Description
I know based on research that upgrades usually break meteor component but is there anyway to fix this asap.

**Comment by tomscholz** [comment]
What is broken? Can you provide some kind of error log?

**Comment by kevinrfx8** [comment]
```node
=> Started proxy.                             
=> Meteor 1.4.4.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While loading package materialize:materialize@0.98.2:
   error: Command failed:
   /root/.meteor/packages/meteor-tool/.1.4.4_1.4figcf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
   rebuild --update-binary
   node-pre-gyp ERR! Tried to download:
   https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v46-linux-x64.tar.gz 
   node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.15 and
   node@4.8.1 (node-v46 ABI) (falling back to source compile with node-gyp) 
   Error extracting archive
   Phantom installation failed { [Error: Command failed: tar jxf
   /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
   tar (child): bzip2: Cannot exec: No such file or directory
   tar (child): Error is not recoverable: exiting now
   tar: Child returned status 2
   tar: Error is not recoverable: exiting now
   ]
   killed: false,
   code: 2,
   signal: null,
   cmd: 'tar jxf /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2' } Error:
   Command failed: tar jxf /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
   tar (child): bzip2: Cannot exec: No such file or directory
   tar (child): Error is not recoverable: exiting now
   tar: Child returned status 2
   tar: Error is not recoverable: exiting now
   
   at ChildProcess.exithandler (child_process.js:200:12)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at maybeClose (internal/child_process.js:862:16)
   at Socket.<anonymous> (internal/child_process.js:338:11)
   at emitOne (events.js:77:13)
   at Socket.emit (events.js:169:7)
   at Pipe._onclose (net.js:490:12)
   npm ERR! code ELIFECYCLE
   npm ERR! errno 1
   npm ERR! phantomjs@1.9.20 install: `node install.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the phantomjs package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node install.js
   npm ERR! You can get information on how to open an issue for this project
   with:
   npm ERR!     npm bugs phantomjs
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls phantomjs
   npm ERR! There is likely additional logging output above.
   
   npm ERR! A complete log of this run can be found in:
   npm ERR!
   /root/.meteor/packages/meteor-tool/.1.4.4_1.4figcf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-05-12T06_02_15_094Z-debug.log
   node-pre-gyp ERR! Tried to download:
   https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v46-linux-x64.tar.gz 
   node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.15 and
   node@4.8.1 (node-v46 ABI) (falling back to source compile with node-gyp) 
   Error extracting archive
   Phantom installation failed { [Error: Command failed: tar jxf
   /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
   tar (child): bzip2: Cannot exec: No such file or directory
   tar (child): Error is not recoverable: exiting now
   tar: Child returned status 2
   tar: Error is not recoverable: exiting now
   ]
   killed: false,
   code: 2,
   signal: null,
   cmd: 'tar jxf /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2' } Error:
   Command failed: tar jxf /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
   tar (child): bzip2: Cannot exec: No such file or directory
   tar (child): Error is not recoverable: exiting now
   tar: Child returned status 2
   tar: Error is not recoverable: exiting now
   
   at ChildProcess.exithandler (child_process.js:200:12)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at maybeClose (internal/child_process.js:862:16)
   at Socket.<anonymous> (internal/child_process.js:338:11)
   at emitOne (events.js:77:13)
   at Socket.emit (events.js:169:7)
   at Pipe._onclose (net.js:490:12)
   npm ERR! code ELIFECYCLE
   npm ERR! errno 1
   npm ERR! phantomjs@1.9.20 install: `node install.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the phantomjs package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node install.js
   npm ERR! You can get information on how to open an issue for this project
   with:
   npm ERR!     npm bugs phantomjs
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls phantomjs
   npm ERR! There is likely additional logging output above.
   
   npm ERR! A complete log of this run can be found in:
   npm ERR!
   /root/.meteor/packages/meteor-tool/.1.4.4_1.4figcf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-05-12T06_02_15_094Z-debug.log
   
   
=> Your application has errors. Waiting for file change.
```
