### ISSUE TITLE
I have this problem when installing materialize in meteor please as I can solve it

### ISSUE THREAD

**Issue by NatalyAlvarez8655176** [Dogfalo/materialize#4697]
```
nataly@nataly-HP-1000-Notebook-PC:~/Escritorio/proyecto/proyecto$ meteor add materialize:materialize
=> It looks like a simple tweak to your system's configuration will
   make many tools (including this Meteor command) more efficient. To
   learn more, see
   https://github.com/meteor/meteor/wiki/File-Change-Watcher-Efficiency
 => Errors while adding packages:             
                                              
While loading package materialize:materialize@0.98.2:
error: Command failed:
/home/nataly/.meteor/packages/meteor-tool/.1.4.4_2.10w6pav++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/npm
rebuild --update-binary
node-pre-gyp ERR! Tried to download:
https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v46-linux-ia32.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.15 and
node@4.8.2 (node-v46 ABI) (falling back to source compile with
node-gyp) 
make: g++: No se encontró el programa
make: *** [Release/obj.target/.node] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command
"/home/nataly/.meteor/packages/meteor-tool/.1.4.4_2.10w6pav++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node"
"/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/node-gyp/bin/node-gyp.js"
"build" "--fallback-to-build"
"--module=/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32/fse.node"
"--module_name=fse"
"--module_path=/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32"
gyp ERR! cwd
/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents
gyp ERR! node -v v4.8.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute
'/home/nataly/.meteor/packages/meteor-tool/.1.4.4_2.10w6pav++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node
/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/node-gyp/bin/node-gyp.js
build --fallback-to-build
--module=/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32/fse.node
--module_name=fse
--module_path=/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32'
(1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous>
(/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose
(internal/child_process.js:862:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:222:5)
node-pre-gyp ERR! System Linux 3.16.0-30-generic
node-pre-gyp ERR! command
"/home/nataly/.meteor/packages/meteor-tool/.1.4.4_2.10w6pav++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node"
"/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents/node_modules/.bin/node-pre-gyp"
"install" "--fallback-to-build"
node-pre-gyp ERR! cwd
/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents
node-pre-gyp ERR! node -v v4.8.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fsevents@1.0.15 install: `node-pre-gyp install
--fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.15 install script 'node-pre-gyp
install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm
installed.
npm ERR! If you do, this is most likely a problem with the fsevents
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this
project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
/home/nataly/.meteor/packages/meteor-tool/.1.4.4_2.10w6pav++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/.npm/_logs/2017-05-16T15_43_02_891Z-debug.log
node-pre-gyp ERR! Tried to download:
https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v46-linux-ia32.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.15 and
node@4.8.2 (node-v46 ABI) (falling back to source compile with
node-gyp) 
make: g++: No se encontró el programa
make: *** [Release/obj.target/.node] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command
"/home/nataly/.meteor/packages/meteor-tool/.1.4.4_2.10w6pav++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node"
"/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/node-gyp/bin/node-gyp.js"
"build" "--fallback-to-build"
"--module=/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32/fse.node"
"--module_name=fse"
"--module_path=/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32"
gyp ERR! cwd
/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents
gyp ERR! node -v v4.8.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute
'/home/nataly/.meteor/packages/meteor-tool/.1.4.4_2.10w6pav++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node
/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/node-gyp/bin/node-gyp.js
build --fallback-to-build
--module=/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32/fse.node
--module_name=fse
--module_path=/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32'
(1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous>
(/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose
(internal/child_process.js:862:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:222:5)
node-pre-gyp ERR! System Linux 3.16.0-30-generic
node-pre-gyp ERR! command
"/home/nataly/.meteor/packages/meteor-tool/.1.4.4_2.10w6pav++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node"
"/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents/node_modules/.bin/node-pre-gyp"
"install" "--fallback-to-build"
node-pre-gyp ERR! cwd
/home/nataly/.meteor/packages/materialize_materialize/.0.98.2.3fw8vz++os+web.browser+web.cordova/npm/node_modules/.temp-nvivy1/node_modules/fsevents
node-pre-gyp ERR! node -v v4.8.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fsevents@1.0.15 install: `node-pre-gyp install
--fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.15 install script 'node-pre-gyp
install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm
installed.
npm ERR! If you do, this is most likely a problem with the fsevents
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this
project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
/home/nataly/.meteor/packages/meteor-tool/.1.4.4_2.10w6pav++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/.npm/_logs/2017-05-16T15_43_02_891Z-debug.log
```

**Comment by tomscholz** [comment]
Please check https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=%20label%3Ameteor%20 for duplicate issues.
