### ISSUE TITLE
Undefined variables in a node environment cause testing issues

### ISSUE THREAD

**Issue by shadedesignz** [Dogfalo/materialize#5519]
## Expected Behavior
Expecting to be able to use materialize in a Node environment when testing code. Currently, I am required to create 3 global variables in my Mocha/Node testing environment for materialize to not fall on it's face.

## Current Behavior
Doing a simple require of materialize in a node/mocha testing environment results in an error:

> Note: Line 60 of the setup file is just `const Materialize = require('materialize-css')`

```js
my-project/node_modules/materialize-css/dist/js/materialize.js:1070
  M.jQueryLoaded = !!window.jQuery;

ReferenceError: M is not defined
    at my-project/node_modules/materialize-css/dist/js/materialize.js:1070:3
    at Object.<anonymous> (my-project/node_modules/materialize-css/dist/js/materialize.js:1071:3)
    at Module._compile (module.js:660:30)
    at Module.replacementCompile (my-project/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (my-project/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (my-project/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (my-project/test/setup.js:60:21)
```

Fixed by setting a global environment variable of `global.M = {}`;

```js
my-project/node_modules/materialize-css/dist/js/materialize.js:2131
})(cash, M.anime);
   ^

ReferenceError: cash is not defined
    at Object.<anonymous> (/my-project/node_modules/materialize-css/dist/js/materialize.js:2131:4)
    at Module._compile (module.js:660:30)
    at Module.replacementCompile (/my-project/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/my-project/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/my-project/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/my-project/test/setup.js:60:21)
```

Fixed by setting a global environment variable of `global.cash = $`; (Note $ has been required)

```js
my-project/node_modules/materialize-css/dist/js/materialize.js:1044
      if (els instanceof Element) {
                         ^

ReferenceError: Element is not defined
    at Function.init (my-project/node_modules/materialize-css/dist/js/materialize.js:1044:26)
    at Function.init (my-project/node_modules/materialize-css/dist/js/materialize.js:11847:84)
    at my-project/node_modules/materialize-css/dist/js/materialize.js:11876:9
    at Object.<anonymous> (my-project/node_modules/materialize-css/dist/js/materialize.js:11877:3)
    at Module._compile (module.js:660:30)
    at Module.replacementCompile (my-project/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (my-project/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (my-project/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (my-project/test/setup.js:60:21)
```

Fixed by setting a global environment variable of `global.Element = class Element {}`;

## Possible Solution
Verify that all variables have been defined and are not being assumed elsewhere

## Steps to Reproduce (for bugs)

1. Have a node/mocha environment
2. In a mocha test, require Materialize
3. Attempt to run the test

## Context
Just trying to run test without extra overhead

## Environment
OS: macOS High Sierra (v10.13.2)
Environment: Node (v9.3.0)
Testing Framework: Mocha (v4.1.0)
Materialize Version: 1.0.0-alpha.3 (occurs in alpha.1 & alpha.2 requiring an explicit need for anime.min.js)
Project: Unable to disclose

**Comment by DanielRuf** [comment]
The import / require should be `M`. Do you use webpack or some other treeshaking solution?

**Comment by shadedesignz** [comment]
There is no library being used, it is in a node testing environment therefore webpack would be a useless factor.

The issue appears to be that there is an inconsistent declaration for these key variables. Via a bundles `materialize.js` file, starting at line 1062.

The only two declarations for 'M' are `M = or `window.M =`.
In a node environment window.M !== M. Therefore on line 1070, `M.jQueryLoaded = ...` is attempting to add a property to an undefined variable.

Not to mention that within the entire file, even when M is being used, it is not declared via any sort of `var`, `let`, or `const`. (Expecting var in the bundled file). This is acceptable for window.M, due to window's global declaration from the browser in a non-node environment.

Next the same issue basically is happening with the `cash` variable. It is assigned to the `window.cash` scope, making it's first use on line 2131 undefined.

The final issue using `Element` is due to an expectancy again for `Element` to exist in a global scope since it is part of the `window` scope.

**Comment by DanielRuf** [comment]
cc @Dogfalo @tomscholz I guess we need the proper UMD/AMD/CJS/module definition there.

**Comment by ghowell** [comment]
issue's still there, I had to add those same 3 var declarations.  thanks for pointing out whats up shadedesignz.
