### ISSUE TITLE
Unable to add materialize on Windows

### ISSUE THREAD

**Issue by davinderkumar** [Dogfalo/materialize#5646]
Node: 8.9.4
NPM : 5.6.0
Meteor: 1.6.1

Command:  meteor add materialize:materialize

```
PS D:\Work\myaddresspin\app> meteor add materialize:materialize
 => Errors while adding packages:

While loading package materialize:materialize@0.100.2:
error: Command failed: C:\WINDOWS\system32\cmd.exe /c C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd rebuild
--update-binary
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.2/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.1\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe',
gyp verb cli   'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.1
gyp info using node@8.9.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\python\python.exe" in the
PATH
gyp verb `which` succeeded C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\python\python.exe
C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\python\python.exe
gyp verb check python version `C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\python\python.exe -c "import platform;
print(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir compiling against specified --nodedir dev files: C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle
gyp verb build dir attempting to create "build" dir:
C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\.temp-1l1v3nz.8908k\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created?
C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\.temp-1l1v3nz.8908k\node_modules\node-sass\build
gyp verb Not using VS2017: Could not use PowerShell to find VS2017
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file:
C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\.temp-1l1v3nz.8908k\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file:
C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\.temp-1l1v3nz.8908k\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file:
C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\.temp-1l1v3nz.8908k\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\python\python.exe
gyp info spawn args [ 'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\.temp-1l1v3nz.8908k\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.1\\mt-os.windows.x86_64\\dev_bundle\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.1\\mt-os.windows.x86_64\\dev_bundle',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args
'-Dmodule_root_dir=C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\.temp-1l1v3nz.8908k\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args
'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\.temp-1l1v3nz.8908k\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.1\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext="
"--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\.temp-1l1v3nz.8908k\node_modules\node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Davinder\AppData\Roaming\npm-cache\_logs\2018-02-07T17_49_21_545Z-debug.log
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.2/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.1\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe',
gyp verb cli   'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.1
gyp info using node@8.9.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\python\python.exe" in the
PATH
gyp verb `which` succeeded C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\python\python.exe
C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\python\python.exe
gyp verb check python version `C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\python\python.exe -c "import platform;
print(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir compiling against specified --nodedir dev files: C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle
gyp verb build dir attempting to create "build" dir:
C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\.temp-1l1v3nz.8908k\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created?
C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\.temp-1l1v3nz.8908k\node_modules\node-sass\build
gyp verb Not using VS2017: Could not use PowerShell to find VS2017
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file:
C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\.temp-1l1v3nz.8908k\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file:
C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\.temp-1l1v3nz.8908k\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file:
C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\.temp-1l1v3nz.8908k\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\python\python.exe
gyp info spawn args [ 'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\.temp-1l1v3nz.8908k\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.1\\mt-os.windows.x86_64\\dev_bundle\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.1\\mt-os.windows.x86_64\\dev_bundle',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args
'-Dmodule_root_dir=C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\.temp-1l1v3nz.8908k\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args
'C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\.temp-1l1v3nz.8908k\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\Davinder\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.1\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Davinder\\AppData\\Local\\.meteor\\packages\\materialize_materialize\\0.100.2\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext="
"--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Davinder\AppData\Local\.meteor\packages\materialize_materialize\0.100.2\npm\node_modules\.temp-1l1v3nz.8908k\node_modules\node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Davinder\AppData\Roaming\npm-cache\_logs\2018-02-07T17_49_21_545Z-debug.log
```

**Comment by DanielRuf** [comment]
Please try installing https://github.com/felixrieseberg/windows-build-tools

**Comment by davinderkumar** [comment]
Thanks
