### ISSUE TITLE
Can't use this package with meteor add materialize:materialize

### ISSUE THREAD

**Issue by tidus89** [Dogfalo/materialize#6205]
Can't use this package...
If I do meteor add materialize:materialize I get the following error.
It seems that the site  "https://github.com/sass/node-sass/releases/download/v4.5.2/linux-x64-57_binding.node" is no longer accessible so I guess that has to be changed?

While loading package materialize:materialize@0.100.2:
error: Command failed: /home/tidus89/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm rebuild --update-binary
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.2/linux-x64-57_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g. 

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [ '/home/tidus89/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node',
gyp verb cli   '/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.1
gyp info using node@8.11.4 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.15rc1\n"
gyp verb get node dir compiling against specified --nodedir dev files: /home/tidus89/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle
gyp verb build dir attempting to create "build" dir: /home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/tidus89/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/tidus89/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle',
gyp info spawn args   '-Dnode_gyp_dir=/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/tidus89/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: g++: Command not found
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/home/tidus89/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd /home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tidus89/.npm/_logs/2018-11-11T16_35_01_113Z-debug.log
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.2/linux-x64-57_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g. 

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [ '/home/tidus89/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node',
gyp verb cli   '/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.1
gyp info using node@8.11.4 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.15rc1\n"
gyp verb get node dir compiling against specified --nodedir dev files: /home/tidus89/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle
gyp verb build dir attempting to create "build" dir: /home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/tidus89/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/tidus89/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle',
gyp info spawn args   '-Dnode_gyp_dir=/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/tidus89/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: g++: Command not found
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/home/tidus89/.meteor/packages/meteor-tool/.1.8.0.1gdnmok.4nus++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd /home/tidus89/.meteor/packages/materialize_materialize/.0.100.2.leviho.nbzw++os+web.browser+web.cordova/npm/node_modules/.temp-wgvhtr.gwnna/node_modules/node-sass
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tidus89/.npm/_logs/2018-11-11T16_35_01_113Z-debug.log

**Comment by ckiw** [comment]
same here

**Comment by Blondint** [comment]
You can see this related issue

#5275
