### ISSUE TITLE
Materialize JS don't work in express SSR.

### ISSUE THREAD

**Issue by jdrupal-dev** [Dogfalo/materialize#6477]
I have a react app that use an express server for server side rendering.

If I call `import M from 'materialize-css/dist/js/materialize.min';` in app JS and start my app is says: 
> ReferenceError: window is not defined
[0]     at Object.<anonymous> (/Users/User/Sites/task_keeper/node_modules/materialize-css/dist/js/materialize.min.js:6:1135)
[0]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[0]     at Module.load (internal/modules/cjs/loader.js:653:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[0]     at Module.require (internal/modules/cjs/loader.js:692:17)
[0]     at require (internal/modules/cjs/helpers.js:25:18)
[0]     at eval (webpack:///external_%22materialize-css/dist/js/materialize.min%22?:1:18)

Is this a bug, or if not, how can I use materialize when rendering my react app server side?

**Comment by DanielRuf** [comment]
`window` is not defined in this context which is correct. Normally you shim that.
